using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ADHelper.Config {
    class WordList5 {

        // a pruned set of 5 letter words sourced from
        // https://www.trvst.world/mind-body/positive-words/5-letter-words/

        public static string[] Words = {
            "Adept",
            "Agile",
            "Alert",
            "Alive",
            "Amity",
            "Bless",
            "Bonus",
            "Brave",
            "Brisk",
            "Champ",
            "Cheer",
            "Clean",
            "Clear",
            "Dream",
            "Excel",
            "Faith",
            "Favor",
            "Feast",
            "Fleet",
            "Gleam",
            "Glint",
            "Glory",
            "Grace",
            "Grand",
            "Grasp",
            "Great",
            "Gusto",
            "Happy",
            "Heart",
            "Honor",
            "Humor",
            "Ideal",
            "Jewel",
            "Jolly",
            "Laser",
            "Laugh",
            "Loyal",
            "Loyal",
            "Lucky",
            "Lyric",
            "Merit",
            "Merry",
            "Might",
            "Mirth",
            "Moral",
            "Moral",
            "Nifty",
            "Noble",
            "Noble",
            "Oasis",
            "Peace",
            "Prime",
            "Prize",
            "Quick",
            "Rally",
            "Ready",
            "Reign",
            "Relax",
            "Renew",
            "Right",
            "Risen",
            "Royal",
            "Royal",
            "Savvy",
            "Scope",
            "Sheen",
            "Shine",
            "Skill",
            "Sleek",
            "Smile",
            "Solid",
            "Squad",
            "Stage",
            "Stout",
            "Sunny",
            "Sweep",
            "Swift",
            "Tough",
            "Trust",
            "Ultra",
            "Unite",
            "Verve",
            "Vigor",
            "Voice",
            "Wield",
            "Youth"
        };
    }
}
